version: '3'

services:
  redis:
    container_name: redis
    image: redis:4.0-alpine
    ports:
      - "6379:6379"
    expose:
      - 6379
    restart:
      always
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/ssl:/ssl/
    environment:
      - NGINX_HOST=example.com
      - NGINX_PORT=80
    ports:
      - "443:443/tcp"
      - "80:80/tcp"
    links:
      - api
  api:
    container_name: api
    image: handshake-server
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - "8080:8080/tcp"
    environment:
      - DATA_REDIS_HOST=redis
      - TWILIO=${TWILIO}
      - TWILIO_TTL=${TWILIO_TTL}
      - TWILIO_TOKEN=${TWILIO_TOKEN}
      - DEBUG=signal:*
    links:
      - redis
    command: npm run start:docker