version: '3'

services:
  redis:
    container_name: redis
    image: redis:4.0-alpine
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /home/ubuntu/dbdata:/dbdata/
#    ports:
#      - "6379:6379"
    expose:
      - 6379
    restart:
      always
    sysctls:
      - net.core.somaxconn=1024
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"
    command: redis-server /usr/local/etc/redis/redis.conf
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/ssl:/ssl/
    ports:
      - "443:443/tcp"
      - "80:80/tcp"
    expose:
      - 3000
    links:
      - api
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    image: handshake-server
    env_file:
      - .env
    depends_on:
      - redis
    expose:
      - "3000"
    environment:
      - DATA_REDIS_HOST=redis
      - TWILIO=${TWILIO}
      - TWILIO_TTL=${TWILIO_TTL}
      - TWILIO_TOKEN=${TWILIO_TOKEN}
      - DEBUG=signal:*
    links:
      - redis
    sysctls:
      - net.core.somaxconn=1024
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"
    command: npm run start:docker
